branches:
  except:
  - donttestme
language: bash
sudo: required
services:
- docker
install:
- travis_wait make build-no-cache
script:
- make generate-accounts run fixtures tests
after_script:
- make clean
